language: java
jdk:
  - openjdk8

branches:
  only:
    - master

#Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r chc853-springboot2-webservice project1
  - mkdir -p deploy
  - mv chc853-springboot2-webservice.zip deploy/chc853-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: chc853-springboot-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

#CI 실행완료시 메일로 알림
notifications:
  email:
    recipients:
      - chc853@gmail.com
